apiVersion: v1
kind: Service
metadata:
  name: java-api
  labels:
    app.kubernetes.io/name: java-api
    app.kubernetes.io/part-of: gitops-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: java-api
  ports:
    - name: http
      port: 80
      targetPort: http

